[package]
name = "trace3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "bimbam"
path = "src/bimbam.rs"


[dependencies]
rustpython-parser = "0.2.0"

